import React, { useMemo, useState } from 'react';
import { Copy, Download, Paintbrush } from 'lucide-react';
import { useAppContext } from '../store';
import { generateScript } from '../generator';

function syntaxHighlight(cmd: string, enabled: boolean) {
  if (!enabled) {
    return <span className={cmd.startsWith('#') ? 'text-emerald-600 dark:text-emerald-500/70' : 'text-text-main'}>{cmd}</span>;
  }

  if (cmd.startsWith('#')) {
    return <span className="text-emerald-600 dark:text-emerald-500/70">{cmd}</span>;
  }

  const parts = cmd.split(/(\s+|=)/);

  return (
    <>
      {parts.map((part, i) => {
        if (part.startsWith('/')) {
          return <span key={i} className="text-brand-color">{part}</span>;
        }
        if (part === '=') {
          return <span key={i} className="text-text-muted">{part}</span>;
        }
        if (part.match(/^"?[0-9.\/Mkm]+"?$/)) {
          return <span key={i} className="text-emerald-600 dark:text-emerald-400">{part}</span>;
        }
        if (part.startsWith('"') && part.endsWith('"')) {
          return <span key={i} className="text-emerald-600 dark:text-emerald-400">{part}</span>;
        }
        if (parts[i+1] === '=' || (i > 0 && parts[i-1] === '=')) {
            if (i > 0 && parts[i-1] === '=') {
               return <span key={i} className="text-text-main font-semibold">{part}</span>; 
            }
            return <span key={i} className="text-amber-600 dark:text-amber-400 indent-key">{part}</span>;
        }
        return <span key={i} className="text-text-main">{part}</span>;
      })}
    </>
  );
}

export function OutputPanel() {
  const { state } = useAppContext();
  const [syntaxEnabled, setSyntaxEnabled] = useState(true);
  
  const script = useMemo(() => generateScript(state), [state]);

  const handleCopy = () => {
    navigator.clipboard.writeText(script);
  };

  const handleDownload = () => {
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'mikrotik-config.rsc';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full xl:w-[440px] h-full flex flex-col bg-sidebar-bg border-l border-border shrink-0 shadow-[-10px_0_30px_rgba(0,0,0,0.05)] z-10 relative">
      <div className="p-4 border-b border-border flex items-center justify-between">
        <span className="text-[10px] uppercase tracking-[0.2em] font-bold text-text-muted flex items-center gap-2">
          Preview: output.rsc
        </span>
        <div className="flex gap-2">
          <button 
            onClick={() => setSyntaxEnabled(!syntaxEnabled)}
            className={`p-1.5 rounded transition-colors ${syntaxEnabled ? 'text-brand-color bg-brand-color/10 hover:bg-brand-color/20' : 'text-text-muted hover:text-text-main hover:bg-border'}`}
            title={syntaxEnabled ? "Disable Syntax Highlighting" : "Enable Syntax Highlighting"}
          >
            <Paintbrush size={16} />
          </button>
          <button 
            onClick={handleCopy}
            className="p-1.5 hover:bg-border rounded transition-colors text-text-muted hover:text-text-main"
            title="Copy to Clipboard"
          >
            <Copy size={16} />
          </button>
          <button 
            onClick={handleDownload}
            className="p-1.5 hover:bg-border rounded transition-colors text-text-muted hover:text-text-main"
             title="Download .rsc file"
          >
            <Download size={16} />
          </button>
        </div>
      </div>
      <div className="flex-1 p-6 font-mono text-[13px] bg-panel-bg overflow-y-auto selection:bg-brand-color/20 selection:text-brand-color shadow-[inset_0_0_20px_rgba(0,0,0,0.03)] dark:shadow-[inset_0_0_20px_rgba(0,0,0,0.2)]">
        {script ? (
          <div>
            <div className="text-text-muted border-b border-border pb-2 mb-4 italic"># Generated by MikroTik CLI Generator</div>
            {script.split('\n').map((line, i) => (
               <div key={i} className={line.startsWith('#') ? 'mb-1 mt-4 text-emerald-600 dark:text-emerald-500/70 font-semibold tracking-wide' : 'pl-4 mb-0.5 border-l-2 border-transparent hover:border-brand-color/30 transition-colors'}>
                 {syntaxHighlight(line, syntaxEnabled)}
               </div>
            ))}
          </div>
        ) : (
          <span className="text-text-muted/50 italic flex flex-col items-center justify-center h-full gap-4">
             <div className="w-16 h-16 rounded-full border-2 border-dashed border-border flex items-center justify-center text-border">
                <Paintbrush size={24} />
             </div>
             No configuration added yet
          </span>
        )}
      </div>
    </div>
  );
}
